runtime: nodejs
env: flex

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "20"

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10


handlers:
# Serve static files (e.g., images, JS, CSS) from the dist folder
- url: /(dist)/(.+)
  static_files: \1/\2
  upload: dist/(.+)
  secure: always

# Fallback to dynamic handler for other URLs
- url: /.*
  script: auto
  secure: always


env_variables:
  NODE_ENV: 'development'
