runtime: nodejs
env: flex

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "20"

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
- url: /img
  static_dir: public/img

- url: /scripts
  static_dir: public/scripts

- url: /dist
  static_dir: public/dist

- url: /(.*\.(json|ico|txt))
  static_files: public/\1
  upload: public/.*\.(json|ico|txt)

# Serve the main 'index.html' file when the root URL is accessed.
- url: /
  static_files: public/index.html
  upload: public/index.html

# Define a catch-all handler to serve index.html for all other requests,
# enabling HTML5 pushState style navigation.
- url: /.*
  static_files: public/index.html
  upload: public/index.html


env_variables:
  NODE_ENV: 'development'
